### ISSUE TITLE
Handle Pause/Continue DAP commands

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-debug#12]
`DAPodil` currently assumes the `stopOnEntry` argument to the `Initialize` command is `true`, and only allows `Next` commands. `Next` is implemented as offering a value onto a queue that the `Debugger` is blocked on.

To handle `Continue` and `Pause`, we need to use something other than a queue, since to `Continue` we would have to continuously offer new items into the queue, which isn't feasible.

**Comment by jw3** [comment]
Yes for continue we could set a flag, or enter a state, where a command is not needed.

While thinking about this also consider #16
