### ISSUE TITLE
Relay infoset

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-debug#13]
This is complex as it is a "nested" variable that is relayed asynchronously and on-demand: https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Variables

**Comment by arosien** [comment]
Alternatively, the infoset could be a separate "virtual" document: https://code.visualstudio.com/api/extension-guides/virtual-documents.

**Comment by arosien** [comment]
@jw3 @shanedell @kirkejohnson

DAP supports the notion of [loaded scripts](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_access-loaded-scripts)/[loaded sources](https://microsoft.github.io/debug-adapter-protocol/specification#Events_LoadedSource) which is, as I understand it, for viewing linked/related sources of the debug target. The sources are provided by the debugee, and can reference both "real" and virtual (content provided by the debugee itself) sources. 

This functionality is complementary to the [virtual document](https://code.visualstudio.com/api/extension-guides/virtual-documents) mechanism of the VS Code extension system, so I'm wondering if we can use loaded sources of DAP to accomplish what we were thinking with a custom event + extension hooks to view the infoset and data source.

I've prototyped using loaded sources--which supports content-changed notifications--and inserted an animated gif below. The components of the UI that change are:

- The left-hand section with the debug "variables" and "stack" has as a "loaded scripts" pane with the schema file, data file, infoset (new), and data dump (new).
- I've opened the infoset (virtual) source, which is a dump of the current state of the infoset. It updates as the parse proceeds. We could have a toggle, or another virtual source, that would show the infoset "diff" view.
- Also open in its own pane is the "data dump", which was previously rendered to the debug console.

(these additional views are only visible if you click on them in the loaded scripts pane)

![sampleWorkspace-1626120101859](https://user-images.githubusercontent.com/31163/125476245-6aa00ee6-2873-461a-a0a9-639499b635e5.gif)

Questions for you: does this seem like an ok MVP view of the infoset and data? I don't think it's much more work for the backend to use a custom event instead, but it would be more work for the frontend.

Misc notes:

- A loaded script has an associated mime type, so I believe this is used to signal how VS Code should render the content (which may be augmented by various extensions, including our own).

**Comment by jw3** [comment]
Yep, I think this would be a good solution for the MVP release.  Nice hack :+1:

**Comment by Shanedell** [comment]
@arosien I also believe this a good solution. 💯 

I believe I have also found to implant the htmlViewer you had mentioned on https://github.com/jw3/example-daffodil-vscode/issues/45 so getting the data dump as its own view should not be to bad, should just be getting the backend to fire the custom event. 

I hope infoset diff view would be similar but can't be for sure as I have not looked into it much. But I think honestly leaving it as what you have going above wouldn't be a bad thing either
