### ISSUE TITLE
Update to Daffodil 3.1.0

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-debug#20]
Bump to RC and then final.

No more publishLocal.

**Comment by arosien** [comment]
I can take this quick.

**Comment by arosien** [comment]
Oops, doesn't look like the 3.1.0-rc1 artifacts are available yet...

**Comment by jw3** [comment]
https://lists.apache.org/thread.html/r85d5f22c7d20694410fa9bf5b8257174156238db787ec42e1f796a80%40%3Cdev.daffodil.apache.org%3E

**Comment by jw3** [comment]
closed in aa4fefd7ae53bae5555ab25538bb984c8b1895df
