### ISSUE TITLE
Output final Infoset

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-debug#30]
Until the Infoset is tied into the frontend (#13) the user has no indication at the end of the parse what the result was.

Could we send the final Infoset across in an OutputEvent, or dump it to the console before DAPodil exits?

**Comment by arosien** [comment]
Ah, it's always the simple things that get forgotten.

At the same time, maybe the launch file / args-to-debug-session can have an optional "infoset output path" where the infoset can be written, perhaps with a "console" variation too?

**Comment by jw3** [comment]
`infosetOutputPath` sounds good.  It will be optional and when set will be either a filesystem path or `console`.  

Unset means no output, or we could make the arg required and say 'none', I dont have a preference there, but it would be useful to have the option to skip the infoset output.

**Comment by arosien** [comment]
I think it should print to the console if unset. If there was a URI for the console, we could just use URIs, but I don't recall a scheme for it.

**Comment by jw3** [comment]
> I think it should print to the console if unset

Sounds good.  The extension allows this property to be set, defaults to unset.

**Comment by arosien** [comment]
> infosetOutputPath

A slight variation which I think is a little better:

```
"infosetOutput": {
  "type": "console" | "none" | "file"
  "path": <path to output for type file>
}
```
