### ISSUE TITLE
Add release procedure docs

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-debug#34]
@jw3 could you document the release procedure you used so I could reproduce? Also any automation would be a nice-to-have.

**Comment by jw3** [comment]
Use `sbt universal:packageBin` to create the package.  The version is generated from a describe of the last tag.

**Comment by jw3** [comment]
Ill add a doc to the repo

**Comment by jw3** [comment]
> Also any automation would be a nice-to-have.

Just got done doing some automated release work with GitHub actions for another project, will translate here pretty smoothly.  Added #40 to track it, keep this for the release procedure doc which Ill throw in the wiki at the same time.

**Comment by arosien** [comment]
Subsumed by #40.
