### ISSUE TITLE
Add Daffodil variables to returned (DAP) variables

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-debug#35]

**Comment by arosien** [comment]
How's this look? (I'm not sure about the namespace part, maybe convert to a hierarchy? I hate navigating trees though...)

![Uploading _Extension_Development_Host__-_jpeg_dfdl_xsd_—_sampleWorkspace.png…]()

**Comment by arosien** [comment]
Another option is to make a tree with the namespace as the top-level branch.

**Comment by arosien** [comment]
Prototype of a tree view:

![_Extension_Development_Host__-_jpeg_dfdl_xsd_—_sampleWorkspace](https://user-images.githubusercontent.com/31163/121959542-ca7d0700-cd19-11eb-91a1-beef4433d57a.png)

**Comment by jw3** [comment]
There are some examples tucked away under TDML files in the daffodil-test project.

https://github.com/apache/daffodil/blob/master/daffodil-test/src/test/resources/org/apache/daffodil/section07/variables/variables.tdml#L28

Might be some others in the https://github.com/DFDLSchemas projects, not sure.

**Comment by arosien** [comment]
Yeah, I looked in DFDLSchemas but there weren't any with variables that I could see. I'll try that link, thanks!

**Comment by arosien** [comment]
Urgh, it's not exactly clear how to extract a valid dfdl.xsd schema from a TDML file....

**Comment by jw3** [comment]
I've done it before for Schematron related things, but don't recall offhand the details.  There was an xsd in that same package, 

https://github.com/apache/daffodil/blob/master/daffodil-test/src/test/resources/org/apache/daffodil/section07/variables/variables_01.dfdl.xsd

My previous search failed to show that, and I didn't look closely at it, but there it is...

**Comment by arosien** [comment]
Namespaces have their own node in the tree:

<img width="912" alt="_Extension_Development_Host__-_jpeg_three_dfdl_xsd_—_sampleWorkspace_and_Parse_scala_—_example-daffodil-debug" src="https://user-images.githubusercontent.com/31163/122245227-66258900-ce7a-11eb-95da-f05c14cd6370.png">

I see variables getting updated (I'm not sure `0` is the actual default value, need to check):

<img width="887" alt="_Extension_Development_Host__-_jpeg_three_dfdl_xsd_—_sampleWorkspace_and_Parse_scala_—_example-daffodil-debug" src="https://user-images.githubusercontent.com/31163/122245340-81909400-ce7a-11eb-89f4-0d52cf9054ea.png">

**Comment by arosien** [comment]
Fixed in 31a1edaa3dfd71ddb71dbd4c6b1e16ed80676662
