### ISSUE TITLE
Add GitHub actions for build and release

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-debug#40]
Add actions on tag push that will generate a release with attached dapodil artifacts.

Will be short lived since we will be moving out of here soon, but will make things much nicer until then.

**Comment by jw3** [comment]
Might be nice to have a nightly build as well.  Can cron with GH actions.

**Comment by arosien** [comment]
I would also use the [sbt-release plugin](https://github.com/sbt/sbt-release) to provide sbt commands that do the tagging and version incrementing for you.

**Comment by arosien** [comment]
Fixed in fbb1cf0.
