### ISSUE TITLE
Request Infoset Dump

### ISSUE THREAD

**Issue by Shanedell** [jw3/example-daffodil-debug#51]
Would be able to update the debugger to send over the current infoset dump during each step of the debugger?

This will allow for us to create an infoset diff view that will update once the currently sent infoset dump differs from the previous infoset dump.

Will help close issue https://github.com/jw3/example-daffodil-vscode/issues/36 and https://github.com/jw3/example-daffodil-vscode/issues/36

**Comment by arosien** [comment]
It emits a `daffodil.infoset` event every time the infoset changes. It might not emit on every step, but it does send the event. (Added in v0.0.9-1, can you confirm?)

**Comment by Shanedell** [comment]
@arosien So it fires that event but does the event send over the data inside of the infoset at the given point in time?

**Comment by arosien** [comment]
Yes, here's the [Typescript schema](https://github.com/jw3/example-daffodil-debug/issues/48#issuecomment-881743149):

```typescript
interface DaffodilInfosetEvent extends Event {
  event: 'daffodil.infoset';

  content: string;

  /** Default to returning the full infoset XML, but enable other encodings like diffs in the future. */
  mimeType: 'text/xml' | string;
}
```

**Comment by arosien** [comment]
Closing as already implemented.
