### ISSUE TITLE
Migrate packages to apache namespace.

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-debug#53]
`org.apache.daffodil.debugger.dap`?

**Comment by jw3** [comment]
Sounds right to me.

Aligns with the package over here https://github.com/apache/daffodil/tree/master/daffodil-runtime1/src/main/scala/org/apache/daffodil/debugger

**Comment by arosien** [comment]
Note this will change the FQDN used by the extension to be `org.apache.daffodil.debugger.dap.DAPodil`, so it should be coupled with the migration of the backend code to co-exist with the extension.

**Comment by arosien** [comment]
Done during migration to example-daffodil-debug.
