### ISSUE TITLE
One time configuration snapshot 

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-debug#56]
How about a custom event that provides a snapshot of the configuration the debugger booted up with?

Right now the primary thing of interest is the path to the data file.  Other interesting things could be added.

```typescript
    export const daffodilConfigEvent = 'daffodil.config';
    export interface DaffodilConfigEvent {
        inputDataPath: string;
    }
```

Of course this path is already available in the IDE since it originates there, but given several different paths of logic that could generate it, and the possibility of multiple endpoints consuming it, passing it back as the authoritative source makes sense for multiple reasons.

**Comment by jw3** [comment]
This flattens any layers of logic or defaults that generate the config, on either client or server side, into just the actual config that the backend is running with.

**Comment by arosien** [comment]
I can emit a `daffodil.config` event after the launch occurs, with a body like:

```json
{
  "launchArgs": {
    "schemaPath": "/Users/arosien/nteligen/example-daffodil-debug/src/main/resources/jpeg.dfdl.xsd",
    "dataPath": "/Users/arosien/nteligen/example-daffodil-debug/src/main/resources/works.jpg",
    "stopOnEntry": true,
    "infosetOutput": {
      "type": "console",
      "bitmap$init$0": true
    }
  },
  "buildInfo": {
    "version": "0.0.10-SNAPSHOT",
    "daffodilVersion": "3.1.0",
    "scalaVersion": "2.12.13"
  },
  "type": "daffodil.config"
}
```

(Ignore the `bitmap$init$0` field, it's a stupid artifact of the stupid reflection-based JSON encoder used by the java-debug DAP library we use.)

**Comment by jw3** [comment]
Yes this is useful :+1:
